spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
app.invite-code=${INVITE_CODE}

app.auto-generate-goals-enabled=${AUTO_GENERATE_GOALS_ENABLED:false}